[build]
  command = "npm install && npm run build:netlify" # Using a simpler build command
  publish = "dist/build/h5" # Updated path for the simplified build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200